### ISSUE TITLE
How to build D2RAssist.exe

### ISSUE THREAD

**Issue by yuelaotou** [misterokaygo/D2RAssist#68]
How to build D2RAssist.exe, please

I just notice that 66578 has fixed, but i can't build it by myself. is there anyone build it and upload, plz

**Comment by ScriptsCSGOslave** [comment]
If you youtube "How To Compile Source Code in Visual Studio!" one of the first hits has a great guide for it. I don't want to link the video since it shows how to clone a RAT from github :)

**Comment by OneXDeveloper** [comment]
Join the discord for assistance. https://discord.gg/5b2B7QrVqa
